### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by vladimir-kokovic** [CruiseControl/cruisecontrol#2]

**Comment by vladimir-kokovic** [comment]
It is not possible to make a build with current git source.
To make successful build it is necessary to change some files according to attached file.
To build run vk-release.sh.

List of files in attached file:
1. checkout.sh -- pull and diff of changed and original files
2. vk-release.sh -- changed main/release.sh
3. build.xml -- changed build.xml
4. main-build.xml -- changed main/build.xml
5. main/test/net/sourceforge/cruisecontrol/builders/AntBuilderTest.java
6. main/test/net/sourceforge/cruisecontrol/sourcecontrols/SVNTest.java
7.reporting/dashboard/test/unit/net/sourceforge/cruisecontrol/dashboard/service/BuildServiceTest.java

[Uploading cc-build-issue.tar.gz…]()

**Comment by evilxyzzy** [comment]
Is there any way to download your patches?  I don't see them attached to this issue.

  -Tom

**Comment by t-dan** [comment]
I think it should be fixed now by commits:

- 836f48f4c4223b7019244091902087e9002d4286
- 35b34fb53ad9aa45a6f8214b9cd1364e6da8bbf5
- 930d26426ff4397c241a12168148bd239a722e73

Just open new issue, it there are still problems with build
